import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header className="pt-10 pb-10">
          <h1 className="text-3xl text-center font-bold">Onepick</h1>
        </header>
        <main className="pr-5 pl-5 pb-10 mr-auto ml-auto w-full max-w-[750px]">
          {children}
        </main>
      </body>
    </html>
  );
}
